### PR TITLE
Update macro utils

### PR DESCRIPTION
**Pull request by jebrando**

### CODE REVIEW

**Comment by dcristoloveanu** [comment]
> #include "azure_c_shared_utility/crt_abstractions.h"

This has to include macro_utils.h
Because it has a dependency on it by using MU_DEFINE_ENUM.

---
Refers to: inc/azure_umqtt_c/mqttconst.h:7 in 20584ff. [](commit_id = 20584ff0d6f182f7cd2f1d371c7ece0457b5bbe0, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
> #include "azure_c_shared_utility/xio.h"

Missing macro_utils.h include

---
Refers to: inc/azure_umqtt_c/mqtt_client.h:7 in 20584ff. [](commit_id = 20584ff0d6f182f7cd2f1d371c7ece0457b5bbe0, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
> #include "azure_umqtt_c/mqtt_message.h"

Missing macro_utils.h include

---
Refers to: src/mqtt_message.c:5 in 20584ff. [](commit_id = 20584ff0d6f182f7cd2f1d371c7ece0457b5bbe0, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
> #include "testrunnerswitcher.h"

Missing macro_utils.h include

---
Refers to: tests/mqtt_client_ut/mqtt_client_ut.c:16 in 20584ff. [](commit_id = 20584ff0d6f182f7cd2f1d371c7ece0457b5bbe0, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
> #include "testrunnerswitcher.h"

Missing macro_utils.h include

---
Refers to: tests/mqtt_codec_ut/mqtt_codec_ut.c:15 in 20584ff. [](commit_id = 20584ff0d6f182f7cd2f1d371c7ece0457b5bbe0, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
> #include "testrunnerswitcher.h"

Missing macro_utils.h include

---
Refers to: tests/mqtt_message_ut/mqtt_message_ut.c:15 in 20584ff. [](commit_id = 20584ff0d6f182f7cd2f1d371c7ece0457b5bbe0, deletion_comment = False)

**Comment by jebrando** [comment]
> #include "azure_c_shared_utility/xio.h"

It's on the line under the one you tagged.

---
In reply to: [476882559](https://github.com/Azure/azure-umqtt-c/pull/42#issuecomment-476882559) [](ancestors = 476882559)

---
Refers to: inc/azure_umqtt_c/mqtt_client.h:7 in 20584ff. [](commit_id = 20584ff0d6f182f7cd2f1d371c7ece0457b5bbe0, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
> #include "azure_c_shared_utility/xio.h"

Oops, my bad on this one.

---
In reply to: [476894025](https://github.com/Azure/azure-umqtt-c/pull/42#issuecomment-476894025) [](ancestors = 476894025,476882559)

---
Refers to: inc/azure_umqtt_c/mqtt_client.h:7 in 20584ff. [](commit_id = 20584ff0d6f182f7cd2f1d371c7ece0457b5bbe0, deletion_comment = False)

**Pull request merged**
